#!/usr/bin/env python3
"""Download + pin the P-3 bake-off model weights (spec section 11).

Pins each source to a fixed revision and records a SHA256 for every weight file
(the section 13 silent-drift guard - the Moonshine CDN weights have no upstream
version tag, so hashing them ourselves is the only pin they get).

    python scripts/fetch_p3_models.py                 # all four configs
    python scripts/fetch_p3_models.py --only moonshine # just one family

Weights land under models/ (git-ignored). Hashes are written to
corpus/p3/model-hashes.md so a re-run can verify them before trusting a number.
Nothing here is a measurement; it only fetches.
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

# Pins confirmed by docs-researcher 2026-08-01 (spec section 11).
PARAKEET_REPO = "istupakov/parakeet-tdt-0.6b-v3-onnx"
PARAKEET_REV = "8f23f0c03c8761650bdb5b40aaf3e40d2c15f1ce"
WHISPER_REPO = "deepdml/faster-whisper-large-v3-turbo-ct2"
WHISPER_REV = "4df90f75321148c3a29a9e2351b7ddf8f5b115a8"

HASH_EXTS = (".onnx", ".bin", ".ort", ".model", ".txt", ".json", ".safetensors")


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def hash_tree(root: Path) -> list[tuple[str, int, str]]:
    """(relative_path, size_bytes, sha256) for every weight file under root."""
    out = []
    for p in sorted(root.rglob("*")):
        if p.is_file() and p.suffix.lower() in HASH_EXTS:
            out.append((str(p.relative_to(root)).replace("\\", "/"), p.stat().st_size, sha256(p)))
    return out


def fetch_hf(repo: str, rev: str, dest: Path) -> None:
    from huggingface_hub import snapshot_download

    dest.mkdir(parents=True, exist_ok=True)
    print(f"  downloading {repo}@{rev[:12]} -> {dest} ...")
    snapshot_download(repo_id=repo, revision=rev, local_dir=str(dest))


def fetch_moonshine(models_dir: Path) -> Path:
    import moonshine_voice as mv
    from moonshine_voice.moonshine_api import ModelArch

    cache = models_dir / "moonshine"
    cache.mkdir(parents=True, exist_ok=True)
    for size, arch in (("small", ModelArch.SMALL_STREAMING),
                       ("medium", ModelArch.MEDIUM_STREAMING)):
        print(f"  downloading Moonshine {size} (en, MIT) -> {cache} ...")
        path, _arch = mv.get_model_for_language("en", arch, cache_root=str(cache))
        print(f"    model dir: {path}")
    return cache


def write_hashes(pieces: dict[str, tuple[Path, str]]) -> None:
    """pieces: name -> (root_dir, provenance_line). Writes corpus/p3/model-hashes.md."""
    out = ["# P-3 model weight pins + SHA256",
           "",
           "Generated by `scripts/fetch_p3_models.py`. Verify these before trusting a",
           "re-run's numbers (spec section 13 silent-drift guard). The Moonshine CDN has",
           "no upstream version tag, so these hashes are its only pin.",
           ""]
    for name, (root, provenance) in pieces.items():
        out += [f"## {name}", "", provenance, ""]
        rows = hash_tree(root) if root.exists() else []
        if not rows:
            out.append("_(not downloaded)_\n")
            continue
        out.append("| file | bytes | sha256 |")
        out.append("|---|---|---|")
        for rel, size, digest in rows:
            out.append(f"| `{rel}` | {size} | `{digest}` |")
        out.append("")
    dest = Path("corpus/p3/model-hashes.md")
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"\nWrote {dest}")


def main(argv) -> int:
    ap = argparse.ArgumentParser(prog="fetch_p3_models.py")
    ap.add_argument("--models-dir", default="models")
    ap.add_argument("--only", choices=("parakeet", "whisper", "moonshine"), default=None,
                    help="Fetch just one family (default: all).")
    args = ap.parse_args(argv)
    md = Path(args.models_dir)

    parakeet_dir = md / "parakeet-tdt-0.6b-v3-onnx"
    whisper_dir = md / "faster-whisper-large-v3-turbo-ct2"

    want = {args.only} if args.only else {"parakeet", "whisper", "moonshine"}
    if "parakeet" in want:
        print("Parakeet TDT 0.6B v3 (ONNX, CC-BY-4.0 - see NOTICE):")
        fetch_hf(PARAKEET_REPO, PARAKEET_REV, parakeet_dir)
    if "whisper" in want:
        print("whisper-large-v3-turbo (CT2, MIT):")
        fetch_hf(WHISPER_REPO, WHISPER_REV, whisper_dir)
    if "moonshine" in want:
        print("Moonshine v2 small + medium (en, MIT):")
        fetch_moonshine(md)

    write_hashes({
        "Parakeet TDT 0.6B v3": (parakeet_dir, f"HF `{PARAKEET_REPO}` @ `{PARAKEET_REV}` - CC-BY-4.0."),
        "whisper-large-v3-turbo (CT2)": (whisper_dir, f"HF `{WHISPER_REPO}` @ `{WHISPER_REV}` - MIT."),
        "Moonshine small+medium": (md / "moonshine", "Moonshine AI CDN via `moonshine-voice`, en models - MIT. No upstream version tag; hashes are the pin."),
    })
    print("Done. Weights are git-ignored under models/; hashes recorded.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
